apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod-vscode-lab
spec:
  acme:
    email: renato@carelli.com.ar
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: vscode-lab-secret-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: traefik
