apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  namespace: cattle-system
  name: letsencrypt-prod-admin-lab
spec:
  acme:
    email: renato@carelli.com.ar
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: admin-lab-secret-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: traefik
