apiVersion: v1
data:
  rancher-admin-secret: YWRtaW46JGFwcjEkbDc4R3N5RnAkeFlzU3FCV3RhM2gwY2l5OXI4Zk1IMAo=
kind: Secret
metadata:
  creationTimestamp: null
  name: rancher-admin-secret
  namespace: cattle-system
