apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgp-key
  namespace: argocd
spec:
  source:
    path: prd/static/pgp-key
    repoURL: 'https://github.com/k3cloud/k3cloud'
    targetRevision: master
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

